name: Build 

on: push

jobs:
  build-linux-image:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v2
      - name: 'Setup Java 11'
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: 'Get Version Number'
        run: |
          ./mvnw --version
      # - name: 'Setup GraalVM Environment'
      #   uses: DeLaGuardo/setup-graalvm@3.0
      #   with:
      #     graalvm-version: '20.3.0.java11'
      # - name: 'Install Native Image Plugin'
      #   run: |
      #     gu install native-image