name: Build Linux e Mac

on: push

jobs:
  build-linux-image:
    name: 'Build Non-Windows Image'
    strategy:
      matrix:
        os: ['ubuntu-18.04', 'macos-latest']
        include:
          - os: 'ubuntu-18.04'
            label: 'linux'
          - os: 'macos-latest'
            label: 'mac'
    runs-on: ${{matrix.os}}
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v2

      - name: 'Setup Java 11'
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: 'Get Version Number'
        run: |
          ./mvnw --version

      - name: 'Packaging uber-jar'
        run: |
          ./mvnw -B clean package -Dquarkus.package.type=uber-jar
          ls -lah target

      - name: 'Upload uber-jar'
        uses: actions/upload-artifact@v2
        with:
          name: projeto-0.0.1-SNAPSHOT-runner.jar
          path: target/projeto-0.0.1-SNAPSHOT-runner.jar

      - name: 'Setup GraalVM Environment'
        uses: DeLaGuardo/setup-graalvm@3.0
        with:
          graalvm-version: '20.3.0.java11'

      - name: 'Install Native Image Plugin'
        run: |
          gu install native-image

      - name: 'Build Native Linux'
        run: |
          ./mvnw -B clean package -Pnative -Dquarkus.native.container-build=false
          ls -lah target

      - name: 'Upload native'
        uses: actions/upload-artifact@v2
        with:
          name: projeto-0.0.1-SNAPSHOT-runner-${{matrix.label}}
          path: target/projeto-0.0.1-SNAPSHOT-runner